
services:
  prometheus:
    image: prom/prometheus:v3.8.0
    volumes:
      - "./prometheus:/etc/prometheus" 
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.10.2
    restart: unless-stopped

  grafana:
    build: 
      context: ./grafana
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      # add dashboards
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      # two dashboards now
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: unless-stopped

  postgres:
    image: postgres:14.20
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data.csv:/data/data.csv
    restart: unless-stopped
